Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using IntenzNews.Models.services;
using IntenzNews.Models.Structs;
using IntenzNews.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IntenzNews.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private readonly NewsServices newsServices;

        public NewsController(NewsServices newsServices)
        {
            this.newsServices = newsServices;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(NewsIndexVm newsVm)
        {
            if (!String.IsNullOrEmpty((string)TempData["FailedToCreate"]))
                ModelState.AddModelError("CreatePostVm.Content", TempData["FailedToCreate"].ToString());
            newsVm.NewsList = await newsServices.GetNewsAsync(HttpContext.User);
            newsVm.HasNews = newsVm.NewsList.Count > 0;
            return View(newsVm);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(CreatePostVm newsVm)
        {
            if (!ModelState.IsValid)
                return View(newsVm);

            var createSucceeded = await newsServices.CreatePostAsync(newsVm, HttpContext.User);
            if (!createSucceeded)
            {
                string s = "Post could not be created";
                TempData["FailedToCreate"] = s;
                return RedirectToAction(nameof(Index));
            }                
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Like(LikedPostVm postVm)
        {
            await newsServices.LikePostAsync(postVm.PostId, HttpContext.User);
            var amountOfLikes = await newsServices.GetLikeCountForPostAsync(postVm.PostId);
            return Json(new LikesAjaxResponseVm { AmountOfLikes = amountOfLikes });
        }

        [HttpPost]        
        public async Task<IActionResult> PostComment(PostNewCommentVm commentVm)
        {
            var currentUser = HttpContext.User;
            var newComment = await newsServices.CommentPostAsync(commentVm.postId, commentVm.Comment, currentUser);
            if (newComment == null)
                return Json(new CommentAjaxResponseVm { PostedSuccessfully = false });
           
            var amountOfComments = await newsServices.GetCommentCountForPostAsync(commentVm.postId);
            return Json( new CommentAjaxResponseVm { CommentCount = amountOfComments, PostedSuccessfully = newComment != null, NewComment = newComment });
        }

        [HttpGet, Authorize(Roles = Roles.Admin), Route("News/" +nameof(DeletePost) + "/{postId}")]
        public async Task<IActionResult>DeletePost(int postId)
        {
            await newsServices.DeletePostAsync(postId);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous, HttpGet]
        [Route("News/" + nameof(GetNextPageOfComments) + "/{postId}/{page}")]
        public async Task<IActionResult> GetNextPageOfComments (int postId, int page)
        {
            var comments = await newsServices.GetNextPageOfCommentsAsync(postId, page);
            return Json(new GetPostCommentsVm { CommentsForPost = comments, NoMoreNews = comments.Count() < 5 });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IntenZ News</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Bootstrap/bootstrap.min.css" rel="stylesheet" />
    <!-- Main CSS -->
    <link href="~/styles/main.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    @RenderSection("styles", false)
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container">
            <a class="navbar-brand" href="#">IntenZ News</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="home" asp-action="index">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="News">News</a>
                    </li>
                    <li class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="account" asp-action="Logout" class="nav-link">Logout</a>
                        }
                        else
                        {
                            <a asp-controller="account" asp-action="Login" class="nav-link">Login</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main id="main-wrapper">

        @RenderBody()
    </main>
    <footer>
        <i class="fab fa-twitter"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-youtube"></i>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Jquery/jquery-3.3.1.min.js"></script>
    <script src="~/Bootstrap/bootstrap.min.js"></script>
    @RenderSection("scripts", false)


</body>

</html>

Views/Shared/_NewsCard.cshtml
@model NewsCardVm
<div class="container news-post">
    <article class="card news-card col-10" data-post="@Model.Id">
        <section class="news-header">
            <h5 class="card-title">@Model.Header</h5>
            @if (User.IsInRole(Roles.Admin))
            {
                <span class="remove-news"><i class="far fa-times-circle"></i></span>
            }
        </section>
        <div id="card-id-@Model.Id" class="card-body">
            <div class="author-date-div">
                <span class="author">@Model.Author</span><span class="published-at">@Model.PublishedAt</span>
            </div>
            <p class="card-text">@Model.Content</p>
            <nav class="card-nav" data-post="@Model.Id">
                <div class="news-like float-left mr-2">
                    @if (Model.Liked)
                    {
                        <i class="fas fa-heart class-icon liked"></i>
                    }
                    else
                    {
                        <i class="fas fa-heart class-icon"></i>
                    }
                    <span class="like-count">@Model.LikesCount</span>
                </div>
                <div class="news-comment">
                    <i class="far fa-comment"></i><span class="comment-count">@Model.CommentCount</span>
                    <span>| Read comments</span><i class="fas fa-angle-down show-comments" data-clicked="false" data-toggle="collapse" data-target="#post-comment-@Model.Id"
                                                   aria-expanded="false" aria-controls="post-comment-@Model.Id"></i>
                </div>
            </nav>
            <div id="post-comment-@Model.Id" class="collapse comment-section">
                <section>
                    <textarea class="form-control comment-input" rows="3"></textarea>
                    <button class="btn-sm btn-danger post-comment pl-3 pr-3 ml-3 mb-3" id="post-comment-@Model.Id">Post</button>
                </section>
                <section class="comments"></section>
                <div class="older-posts">Show older comments</div>
            </div>

        </div>
    </article>
</div>